In [2]:
import pandas as pd
import numpy as np

In [3]:
train_df = pd.read_csv("/Users/bhavyadeepgarg/Downloads/train.csv")
test_df = pd.read_csv("/Users/bhavyadeepgarg/Downloads/test.csv")

In [4]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
count_vect = CountVectorizer()
example_count_vect = count_vect.fit_transform(train_df['text'][0:5])

In [8]:
print(example_count_vect[0].todense().shape)
print(example_count_vect[0].todense())

(1, 54)
[[0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0]]


In [22]:
for i in range(5):
    print(train_df['text'][i])

Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all
Forest fire near La Ronge Sask. Canada
All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected
13,000 people receive #wildfires evacuation orders in California 
Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school 


In [9]:
train_vect = count_vect.fit_transform(train_df['text'])

In [10]:
test_vect = count_vect.transform(test_df['text'])

In [5]:
from sklearn.linear_model import RidgeClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score

In [27]:
xgb1 = XGBClassifier(random_state=123, n_estimators=100, learning_rate=0.8)
scores = cross_val_score(xgb1, train_vect, train_df['target'], cv=5, scoring='f1')

In [20]:
scores

array([0.61284404, 0.51900826, 0.61980831, 0.55614035, 0.67987805])

In [35]:
rdg_clf = RidgeClassifier(random_state=123, alpha=2.0)
scores = cross_val_score(rdg_clf, train_vect, train_df['target'], cv=3, scoring='f1')

In [36]:
scores

array([0.60387513, 0.56648542, 0.65116279])

In [24]:
from sklearn.model_selection import KFold

In [25]:
kf = KFold(shuffle=True, n_splits=5)

In [37]:
cv_results = cross_val_score(rdg_clf, train_vect, train_df['target'], cv=kf, scoring='accuracy')
cv_results

array([0.79317137, 0.80499015, 0.78529219, 0.79303548, 0.79369251])

In [38]:
rdg_clf.fit(train_tfidf_vect, train_df['target'])

RidgeClassifier(alpha=2.0, random_state=123)

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tfidf_vect = TfidfVectorizer()

In [23]:
train_tfidf_vect = tfidf_vect.fit_transform(train_df['text'])
test_tfidf_vect =tfidf_vect.transform(test_df['text'])

In [41]:
cv_results = cross_val_score(rdg_clf, train_tfidf_vect, train_df['target'], cv=kf, scoring='f1')
cv_results

array([0.74290484, 0.74706868, 0.75170068, 0.75862069, 0.75085911])

In [30]:
xgb1.fit(train_tfidf_vect, train_df['target'])

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.8, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=123,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [37]:
from sklearn.naive_bayes import MultinomialNB

In [38]:
mNB = MultinomialNB()

In [40]:
cv_results = cross_val_score(mNB, train_tfidf_vect, train_df['target'], cv=kf, scoring='f1')
cv_results

array([0.7184466 , 0.73021583, 0.73693534, 0.70785525, 0.72958258])

In [50]:
rdg_clf.fit(train_tfidf_vect, train_df['target'])

RidgeClassifier(random_state=123)

In [31]:
sample_submission = pd.read_csv("/Users/bhavyadeepgarg/Downloads/sample_submission.csv")

In [39]:
sample_submission['target']= rdg_clf.predict(test_tfidf_vect)

In [33]:
sample_submission.head()

id  target
0   0       1
1   2       1
2   3       1
3   9       0
4  11       1

In [56]:
test_df['text'].head()

0                   Just happened a terrible car crash
1    Heard about #earthquake is different cities, s...
2    there is a forest fire at spot pond, geese are...
3             Apocalypse lighting. #Spokane #wildfires
4        Typhoon Soudelor kills 28 in China and Taiwan
Name: text, dtype: object

In [40]:
sample_submission.to_csv('/Users/bhavyadeepgarg/Downloads/submission2.csv', index=False)

In [ ]:
from sklearn.model_selection import RN

In [59]:
from sklearn.metrics import f1_score

In [ ]:
f1_score()

In [1]:
train_df

NameError: name 'train_df' is not defined